2025-07-09 11:48:44 [main] INFO  org.testng.internal.Utils - [TestNG] Running:
  C:\Users\kaingale\Desktop\Assignments\master.xml

2025-07-09 11:48:55 [main] INFO  com.tests.BaseTest - == Starting TC_01_ChkOutFunc_ValidateCheckoutFunctionalityTest ==
2025-07-09 11:48:55 [main] INFO  com.tests.BaseTest - navigating to login page
2025-07-09 11:48:57 [main] INFO  com.tests.BaseTest - entering all the sign in details and click on sign in
2025-07-09 11:49:01 [main] INFO  com.tests.BaseTest - searching product, goto product details
2025-07-09 11:49:06 [main] ERROR com.tests.BaseTest - Test failed due to an exception in catch block: Cannot invoke "com.utilities.ScenarioContextForSavingDynamicValues.setContext(String, Object)" because "this.scenarioContext" is null
